version: '2.3'
# if mysql is on real server
# 172.18.0.1 - is current machine host ip in docker network, found out by: https://stackoverflow.com/a/24716645
# socat TCP-LISTEN:3336,fork,bind=172.18.0.1 TCP:127.0.0.1:3306
# if redison real server
# socat TCP-LISTEN:16379,fork,bind=172.18.0.1 TCP:127.0.0.1:6379
# change maximum socket connections
# https://ubuntuforums.org/showthread.php?t=1198281
# sysctl -w net.core.somaxconn=1024
# clear logs:
# truncate -s 0 $(docker inspect --format='{{.LogPath}}' <container_name_or_id>)
# update docker containser for service(s)
# docker-compose up -d --force-recreate --no-deps --build web phpfpm python-socks
services:
    web:
        image: nginx:stable-alpine
        restart: always
        ports:
            - "8043:843"
            - "9043:943"
        volumes:
            - ./logs:/var/log/nginx
            - ./code:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./nginx/self-signed.conf:/etc/nginx/snippets/self-signed.conf

        networks:
            - code-network

    phpfpm:
        image: php-docker:7-fpm-alpine-laravel
        build: ./docker-phpfpm-custom
        restart: always
        volumes:
            - ./code:/code
            # - ./phpfpm/php.ini:/usr/local/etc/php/php.ini
        networks:
            - code-network
        # command: /bin/sh -c 'php /code/spam/artisan migrate;php /code/spam/artisan optimize;php -a'


    # local developement database
    mysql:
        image: 'mariadb'
        restart: always
        ports:
            - '127.0.0.1:3336:3306'
        volumes:
            - ./db-data:/var/lib/mysql
            - ./code:/code
        environment:
            - MYSQL_ROOT_PASSWORD=MY_MYSQL_PWD
        networks:
            - code-network

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        expose:
            - '80'
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: MY_MYSQL_PWD
            PMA_HOST: mysql
            PMA_ABSOLUTE_URI: https://127.0.0.1:9043/pma-mypma/
        networks:
            - code-network

    python-socks:
        # image: python-docker:3.7-alpine
        build: ./docker-python-custom
        restart: always
        sysctls:
            - net.core.somaxconn=32768
        depends_on:
          - mysql
          - redis
          - phpfpm
        volumes:
            - ./code:/code
            - ./logs:/logs
            - ./supervisor/supervisor.conf:/supervisor/supervisor.conf
            - ./supervisor/sock-check.conf:/etc/supervisor/conf.d/sock-check.conf
        networks:
            - code-network
        command: /bin/sh -c 'supervisord -n -c /supervisor/supervisor.conf;'

    python-spam:
        # image: python-docker:3.7-alpine
        # build: ./docker-python-custom
        build: ./docker-python-custom-web-acc
        restart: always
        sysctls:
            - net.core.somaxconn=32768
        cap_add:
            - NET_ADMIN
        depends_on:
          - mysql
          - redis
          - phpfpm
        volumes:
            - ./code:/code
            - ./logs:/logs
            # - ./supervisor/supervisor.conf:/supervisor/supervisor.conf
            - ./supervisor/supervisor.conf:/supervisor/supervisor.conf
            - ./supervisor/mail-spamer.conf:/etc/supervisor/conf.d/mail-spamer.conf
        networks:
            - code-network
        command: /bin/sh -c 'supervisord -n -c /supervisor/supervisor.conf;'

    python-grabber:
        # image: python-docker:3.7-alpine
        build: ./docker-python-custom-web-acc
        restart: always
        shm_size: '4gb'
        sysctls:
            - net.core.somaxconn=32768
        depends_on:
          - mysql
          - redis
          - phpfpm
        volumes:
            - ./code:/code
            - ./logs:/logs
            - ./supervisor/supervisor.conf:/supervisor/supervisor.conf
            - ./supervisor/mail-grabber.conf:/etc/supervisor/conf.d/mail-grabber.conf
        networks:
            - code-network
        command: /bin/sh -c 'supervisord -n -c /supervisor/supervisor.conf;'

    python-mac:
        # image: python-docker:3.7-alpine
        build: ./docker-python-custom-web-acc
        restart: always
        sysctls:
            - net.core.somaxconn=32768
        depends_on:
          - mysql
          - redis
          - phpfpm
        volumes:
            - ./code:/code
            - ./logs:/logs
            - ./supervisor/supervisor.conf:/supervisor/supervisor.conf
            - ./supervisor/mail-account-checker.conf:/etc/supervisor/conf.d/mail-account-checker.conf
            - ./supervisor/ispdb.conf:/etc/supervisor/conf.d/ispdb.conf
        networks:
            - code-network
        command: /bin/sh -c 'supervisord -n -c /supervisor/supervisor.conf;'

    # commonly useless
    # python-downloader:
    #     # image: python-docker:3.7-alpine
    #     build: ./docker-python-custom
    #     restart: always
    #     sysctls:
    #         - net.core.somaxconn=32768
    #     depends_on:
    #       - mysql
    #       - redis
    #       - phpfpm
    #     volumes:
    #         - ./code:/code
    #         - ./logs:/logs
    #         - ./supervisor/supervisor.conf:/supervisor/supervisor.conf
    #         - ./supervisor/mail-intercetion.conf:/etc/supervisor/conf.d/mail-intercetion.conf
    #         - ./supervisor/mail-downloader.conf:/etc/supervisor/conf.d/mail-downloader.conf
    #     networks:
    #         - code-network
    #     command: /bin/sh -c 'supervisord -n -c /supervisor/supervisor.conf;'
    #     # command: /usr/bin/supervisord -c /supervisor/supervisor.conf
    #     # command: /usr/bin/supervisord -n -c /supervisor/supervisor.conf
    #     # command: /usr/bin/supervisord -n -c /etc/supervisor.conf
    #     # command: supervisord -n -c /supervisor/supervisor.conf
    #     # command: /bin/sh -c 'unlink /tmp/supervisor.sock; supervisord -c /supervisor/supervisor.conf'
    
    redis:
        image: redis:5-alpine

        # build: ./docker-redis-custom
        restart: always
        sysctls:
            - net.core.somaxconn=32768
            # - net.ipv4.tcp_max_syn_backlog=8192
            # - vm.overcommit_memory=1
        ports:
            - '127.0.0.1:16379:6379'
        volumes:
            - ./redis-data:/data
        networks:
            - code-network
        command: /bin/sh -c 'redis-server --appendonly yes --maxclients 32768 --tcp-backlog 8192'

networks:
    code-network:
        driver: bridge
